#!/bin/bash
#auto-generate differrnet qualified res to test specific device (used for TV)
#
#now we just support size and dpi, but you can easily extends this.
#bysong

set -x

for size in small normal large xlarge ;
do 
    for dpi in ldpi mdpi hdpi xhdpi nodpi tvdpi;
    do 
       folder=res/values-$size-$dpi
       mkdir -p $folder
       file=auto_generated_res.xml
       touch $folder/$file
       echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<resources>
    <!-- auto-generated by script, do NOT edit this files.-->
    <string name=\"auto_generated_res\">$folder</string>
</resources>" > $folder/$file 
    done;
done;
